FROM operable/go:1.6.3

ENV PATH=${GOPATH}/bin:${PATH}
# Add goveralls for sending stats to coveralls.io in Travis CI
RUN go get github.com/mattn/goveralls
RUN go get github.com/spf13/pflag

COPY . $GOPATH/src/github.com/operable/go-relay
WORKDIR $GOPATH/src/github.com/operable/go-relay
